### ISSUE TITLE
libOAuth.a doesn't support arm64 now

### ISSUE THREAD

**Issue by ducchinhdl** [bengottlieb/Twitter-OAuth-iPhone#121]
Dear,

I'm using libOAuth.a on many project, but now apple doesn't approve the app that doesn't support arm64.

Could you update your lib libOAuth.a to support arm64

Thanks

**Comment by bengottlieb** [comment]
the library has been updated.

**Comment by rbad** [comment]
I realize that this is a bit late to the party, but I tried taking the updated libOAuth.a in an app that used this repo (I'm simply trying to do the minimum possible to update this old app, published in 2013, so that it meets new App Store minimum's of >= iOS 8) but the XCode linker complains "libOAuth.a(Base64Transcoder.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '[path]/libOAuth.a' for architecture arm64". Any ideas would be greatly appreciated!

**Comment by bengottlieb** [comment]
I would disable bitcode for your app, if you absolutely need the library. It's not required by the AppStore.

**Comment by rbad** [comment]
👍
